version: '2.12.2'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-xt4ugx&_)2^zgd8a66kqau37^ib+a%!(&dc#t0rlg6nx_&d%i("
      - "DJANGO_DEBUG=True"

  db:
    image: postgres:15
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
