# Generated by Django 4.0.2 on 2022-12-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_grouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouping',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
