# Generated by Django 4.0.2 on 2022-12-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_grouping_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ManyToManyField(related_name='order', to='products.Grouping'),
        ),
    ]
