# Generated by Django 4.0.2 on 2022-12-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
        migrations.AddField(
            model_name='grouping',
            name='order',
            field=models.ManyToManyField(related_name='group', to='products.Product'),
        ),
    ]
