# Generated by Django 4.0.2 on 2022-12-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_group_grouping_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouping',
            name='order',
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ManyToManyField(related_name='order', to='products.Grouping'),
        ),
    ]
